### PR TITLE
the funky scr_level_dat_add function

### PR DESCRIPTION
**Pull request by JeremyGamer13**
h

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
if i forgor something then tell me or just add it

**Review by thennothinghappened — CHANGES_REQUESTED** [review]
Looks good however make sure to remember two things:
1. If a variable can only be one of two states, `0` or `1`, that means it is `true` or `false`, aka a boolean. Unfortunately this can be hard to tell since the compiler changes it to a real. Make sure to keep that in mind. `lvl_limitedbuild_available` is a bool, `lvl_isboss` is a bool.
2. Please try not to include from the game verbatim because I'm not sure on the legality of that, plus modders can have a look at the function themselves to see exactly what it is, our job is to provide a description which tells them what it does, not what it is.

Other than that, looks good!

**Comment by JeremyGamer13** [comment]
oh yeah i totally forgot about booleans, ill change that

**Comment by JeremyGamer13** [comment]
also i think i also forgot to remove what the function does since i was using it to see what to name the inputs without having to switch tabs with UMT

**Comment by thennothinghappened** [comment]
Have a look at the updated README ("How to contribute"), it will help you with understanding the functions better and quicker than doing it straight from UndertaleModTool.

**Review by thennothinghappened — APPROVED** [review]

**Pull request merged**
